slurmctld now persists state and hook preventing upgrade while jobs queued
stackhpc/slurm-docker-cluster pull request #10
Opened 2023-07-14 08:14 UTC by wtripp180901

2023-07-14 11:01 UTC, sjpb requested changes
I updated the title, which describes _what_ it does. Can you update the first comment in the PR please to outline _how_  it does it (v briefly).

2023-07-17 08:20 UTC, wtripp180901 commented on slurm-cluster-chart/templates/slurmctld-deployment.yaml
>        hostname: slurmctld
I tested it with and without and we seem to need it to persist job numbers between restarts

2023-07-17 08:40 UTC, wtripp180901 commented on docker-entrypoint.sh
> +            echo "Error: cannot upgrade chart - there are still Slurm jobs in the queue"
It's a bit of a weird situation. It is possible to get logs from the hook job, but the job existing after a failed run stops you from attempting another upgrade (gives an 'already exists' message when trying to run the hook) unless it's manually deleted. I'm currently setting it to self delete as soon as the hook finishes, but this means we can't see the logs. I could potentially set it to delete after a minute or something if you think that would be better?

2023-07-18 10:06 UTC, sjpb requested changes
Still a couple of comments.

2023-07-18 10:06 UTC, sjpb commented on docker-entrypoint.sh
> +            echo "Error: cannot upgrade chart - there are still Slurm jobs in the queue"
That's nasty. Can you check whether writing to the termination log helps? See https://kubernetes.io/docs/tasks/debug/debug-application/determine-reason-pod-failure.

If not, I suggest leaving it deleting the job as soon as it finishes, and removing the `echo` as its a bit misleading that this will be e.g. greppable, when it won't be. The code is basically self-documenting, so no need for a comment or anything IMO.

2023-07-18 10:06 UTC, sjpb commented on slurm-cluster-chart/templates/slurmctld-deployment.yaml
>        hostname: slurmctld
Note this was in relation to the `hostname` parameter on the pod, please retest.

2023-07-18 10:12 UTC, sjpb commented on slurm-cluster-chart/templates/slurmctld-deployment.yaml
Should this filename be changed to `slurmctld-statefulset.yml` too?

2023-07-18 14:39 UTC, wtripp180901 commented on slurm-cluster-chart/templates/slurmctld-deployment.yaml
>        hostname: slurmctld
Tested this, doesn't look like it does anything anymore

2023-07-18 14:43 UTC, wtripp180901 commented on docker-entrypoint.sh
> +            echo "Error: cannot upgrade chart - there are still Slurm jobs in the queue"
It looks like termination logs still need the pod running the job to present and that also gets deleted. I'll just take out the echos

2023-07-20 12:15 UTC, sjpb approved these changes

2023-07-20 12:15 UTC, merged