Added Open OnDemand
stackhpc/slurm-docker-cluster pull request #15
Opened 2023-07-19 15:16 UTC by wtripp180901

Has working OOD dashboard when connecting to the login pod's floating IP. Currently has working shell (although timeout issues persists, see ood-shell-timeout-fix), job composer (requires https) and active jobs view

2023-08-11 08:59 UTC, sjpb requested changes

2023-08-11 08:59 UTC, sjpb commented on image/docker-entrypoint.sh
> +    if [ -f /home/rocky/.ssh/id_rsa.pub ]; then
Move this to the "settig self ssh capabilties" section so it's clear why we do this

2023-08-11 08:59 UTC, sjpb commented on image/docker-entrypoint.sh
> +    env > /etc/ood/config/apps/shell/env
I'd really like to know WHY this is required (i.e. in a comment), or if it really is??

2023-08-11 08:59 UTC, sjpb commented on slurm-cluster-chart/files/httpd.conf
> +#
Can we state where this came from e.g.

```suggestion
# Modified from file installed by httpd package
```

2023-08-11 08:59 UTC, sjpb commented on image/Dockerfile
> +    && yum -y install https://yum.osc.edu/ondemand/2.0/ondemand-release-web-2.0-1.noarch.rpm \
This is really annoying of me; now this works, can we try v3?

`https://yum.osc.edu/ondemand/3.0/ondemand-release-web-3.0-1.noarch.rpm`

2023-08-11 08:59 UTC, sjpb commented on slurm-cluster-chart/files/ood_portal.yaml
> +---
Again can we state source:

```suggestion
# Modified from file installed by ondemand package
---
```

2023-08-11 08:59 UTC, sjpb commented on image/docker-entrypoint.sh
> +    env > /etc/ood/config/apps/shell/env
Is it just to get ROCKY_OOD_PASS from the login-deployment?
If so it might be better to directly specify this, e.g. 

`echo ROCKY_OOD_PASS=\"${ROCKY_OOD_PASS}\" > /etc/ood/config/apps/shell/env`

2023-08-11 08:59 UTC, sjpb commented on slurm-cluster-chart/templates/login-service.yaml
> +    - name: "apache"
Nit but can we remove the `"` from round these names for consistency with others? For simple alpha strings (i.e. no spaces, no numbers) bare values is fine in yaml, although quoting anything else is sensible (e.g. git hashes could get converted into a number, if they are e.g. 52356E023 or something, which is surprising/bad!)

2023-08-11 12:55 UTC, wtripp180901 commented on image/Dockerfile
> +    && yum -y install https://yum.osc.edu/ondemand/2.0/ondemand-release-web-2.0-1.noarch.rpm \
Looks like this breaks it because of differences on how auth is done, I'll leave what I've tried so far in the `ood-3.0` branch

2023-08-11 13:13 UTC, wtripp180901 commented on image/docker-entrypoint.sh
> +    env > /etc/ood/config/apps/shell/env
Looks like we don't actually need it

2023-08-15 10:02 UTC, sjpb approved these changes

2023-08-15 10:05 UTC, merged