Converts Rook NFS to a Helm chart and sets it as a Slurm chart dependency
stackhpc/slurm-docker-cluster pull request #23
Opened 2023-08-11 11:33 UTC by sd109

2023-08-11 14:15 UTC, sjpb requested changes

2023-08-11 14:15 UTC, sjpb commented on slurm-cluster-chart/values.yaml
> +  storageClassName: &storageclassname slurm-rook-nfs
After discussion, lets ditch the yaml anchor here and just set a default 
```suggestion
  storageClassName: slurm-rook-nfs
```

2023-08-11 14:15 UTC, sjpb commented on slurm-cluster-chart/values.yaml
> +  storageClassName: *storageclassname
... and then explain, but allow people to call the rook sc something else if they "need" to:
```suggestion
  storageClassName: slurm-rook-nfs # NB this must match storage.storageClassName when using rook
```

2023-08-11 14:15 UTC, sjpb commented on slurm-cluster-chart/values.yaml
> +  capacity: &capacity 10Gi
Leave the yaml anchor, but explain
```suggestion
  capacity: &capacity 10Gi   # NB yaml anchor used so this value is also set for `rooknfs.storageCapacity` if necessary.
```

2023-08-11 14:15 UTC, sjpb commented on slurm-cluster-chart/values.yaml
> +  storageCapacity: *capacity
```suggestion
  storageCapacity: *capacity # size of the underlying RWO PVC used by the NFS server
```

2023-08-11 14:15 UTC, sjpb commented on slurm-cluster-chart/values.yaml
> +rooknfs:
Can we expose the storage class name for the "backing" PVC too, so we can use non-default/faster storage if available?

2023-08-11 14:15 UTC, sjpb commented on slurm-cluster-chart/values.yaml
> +  name: slurmd
```suggestion
  name: slurmd # NB this must match NodeName= in slurm-cluster-chart/files/slurm.conf
```

2023-08-15 13:11 UTC, wtripp180901 commented on generate-secrets.sh
Remind me to add this to the helm chart!

2023-08-15 13:20 UTC, wtripp180901 commented on rooknfs/templates/hooks/pre-delete.yaml
At some point we will want a dedicated role for this with minimal permissions

2023-08-15 13:20 UTC, wtripp180901 approved these changes

2023-08-15 15:15 UTC, sjpb requested changes
Only issue I get is that the removal of no-line-wrapping on generate secrets breaks that script.

2023-08-16 09:20 UTC, sd109 commented on generate-secrets.sh
> +kubectl -n $NAMESPACE create secret generic munge-key-secret \
Did you get to the bottom of this? I can't seem to reproduce it.

2023-08-16 10:03 UTC, sjpb approved these changes

2023-08-16 11:01 UTC, merged