Moved secret generation from scripts to helm
stackhpc/slurm-docker-cluster pull request #24
Opened 2023-08-11 13:59 UTC by wtripp180901

- Randomized secret (i.e database password and munge key) are now generated via a helm pre-install hook
- Pre-install job runs to generate persistent host keys for login node
- Can optionally define a public key in values.yaml as an authorised key for rocky, otherwise assumes the publish-keys.sh script has been run
- Fixed helm releaser workflow and now tags releases with SemVer

2023-08-11 14:48 UTC, sd109 requested changes
Looks good, just a few minor questions / comments

2023-08-11 14:48 UTC, sd109 commented on slurm-cluster-chart/templates/secret-generator-role.yaml
Since these resources are created as pre-install hooks (as is the ServiceAccount), they won't be deleted when the chart is uninstalled. Is this a problem? Could another ServiceAccount be bound to this Role in the future allowing unwanted access to Secrets?

2023-08-11 14:48 UTC, sd109 commented on slurm-cluster-chart/values.yaml
> +openOndemand:
```suggestion
openOnDemand:
```

2023-08-11 14:48 UTC, sd109 commented on slurm-cluster-chart/templates/munge-key-secret.yaml
> +    helm.sh/resource-policy: keep
Is this needed? I think this tells Helm not to remove the resource when the chart is uninstalled

2023-08-11 14:48 UTC, sd109 commented on slurm-cluster-chart/templates/login-deployment.yaml
> +              value: {{ .Values.openOndemand.password }}
```suggestion
              value: {{ .Values.openOnDemand.password }}
```

2023-08-11 14:48 UTC, sd109 commented on image/docker-entrypoint.sh
> +
Do we definitely want to bundle this into the entrypoint script? I think it's cleaner to write the shell commands directly into the Job spec (as done [here](https://github.com/stackhpc/slurm-docker-cluster/blob/4407fbe486a3b78bda85f93ac39fc9adda94d0f6/slurm-cluster-chart/templates/hooks/pre-delete.yaml#L43-L52)) since this task is independent of other entrypoint tasks.

2023-08-11 14:48 UTC, sd109 commented on image/Dockerfile
> +       kubectl \
Remove this if moving ssh key gen out of entrypoint script (see comment on entrypoint.sh)

2023-08-11 14:48 UTC, sd109 commented on image/kubernetes.repo
This also becomes unnecessary if removing `kubectl` commands from entrypoint script since we can use a container image with kubectl pre-installed

2023-08-14 12:55 UTC, wtripp180901 commented on image/docker-entrypoint.sh
> +
We discussed this and decided to continue using the main image to ensure we have an image with both kubectl and open-ssh installed. We will also leave it in the entrypoint for now to standardise how we're running jobs

2023-08-14 12:57 UTC, wtripp180901 commented on image/kubernetes.repo
See above

2023-08-14 12:57 UTC, wtripp180901 commented on image/Dockerfile
> +       kubectl \
See above

2023-08-14 12:59 UTC, wtripp180901 commented on slurm-cluster-chart/templates/secret-generator-role.yaml
Needs some further investigation but we we are fairly sure users need to be assigned permissions to create/patch rolebindings

2023-08-14 13:28 UTC, wtripp180901 commented on slurm-cluster-chart/templates/munge-key-secret.yaml
> +    helm.sh/resource-policy: keep
Looks like we don't need it, I think I put it in there because I thought the resources would get deleted after the pre-install hook finished but looks like not

2023-08-15 14:59 UTC, sd109 requested changes

2023-08-15 14:59 UTC, sd109 commented on slurm-cluster-chart/values.yaml
> +mySQL:
```suggestion
database:
```
MariaDB != MySQL so I'd prefer this heading to be generic. Will also need to change this anywhere in the templates that this value is referenced.

2023-08-16 11:44 UTC, sd109 commented
Tested and working on clean k8s cluster

2023-08-16 11:44 UTC, merged